/**
 * Generate downloadable you.md and you.json from DB profile data.
 */
import type { DbProfile, DbProfileSource } from "./profiles";

export function generateYouJson(profile: DbProfile, sources: DbProfileSource[], verifications: any[]) {
  return {
    $schema: "you/v1",
    username: profile.username,
    name: profile.name,
    tagline: profile.tagline,
    bio: {
      short: profile.bio_short,
      medium: profile.bio_medium,
    },
    location: profile.location,
    website: profile.website,
    voice: profile.voice,
    topics: profile.topics || [],
    values: profile.values_list || [],
    now: profile.now_items || [],
    credibility: profile.credibility || [],
    links: profile.links || [],
    preferences: profile.preferences || {},
    connected_sources: sources.map(s => ({
      platform: s.platform,
      username: s.platform_username,
      display_name: s.display_name,
      status: s.status,
      last_synced: s.last_synced_at,
    })),
    verification: {
      verified: verifications.length > 0,
      signals: verifications.map(v => ({
        type: v.signal_type,
        value: v.signal_value,
        verified_at: v.verified_at,
      })),
    },
    is_claimed: profile.is_claimed,
    created_at: profile.created_at,
    updated_at: profile.updated_at,
  };
}

export function generateYouMd(profile: DbProfile, sources: DbProfileSource[], verifications: any[]): string {
  const lines: string[] = [];
  lines.push(`# ${profile.name || profile.username}`);
  if (profile.tagline) lines.push(`> ${profile.tagline}`);
  lines.push("");

  if (profile.bio_medium || profile.bio_short) {
    lines.push(profile.bio_medium || profile.bio_short || "");
    lines.push("");
  }

  if (profile.location) lines.push(`📍 ${profile.location}`);
  if (profile.website) lines.push(`🔗 ${profile.website}`);
  lines.push("");

  if (profile.topics?.length) {
    lines.push("## Topics");
    profile.topics.forEach(t => lines.push(`- ${t}`));
    lines.push("");
  }

  if (profile.now_items?.length) {
    lines.push("## Now");
    profile.now_items.forEach(n => lines.push(`- ${n}`));
    lines.push("");
  }

  if (profile.values_list?.length) {
    lines.push("## Values");
    profile.values_list.forEach(v => lines.push(`- ${v}`));
    lines.push("");
  }

  if (profile.credibility?.length) {
    lines.push("## Credibility");
    profile.credibility.forEach(c => lines.push(`- ${c}`));
    lines.push("");
  }

  if (sources.length > 0) {
    lines.push("## Connected Sources");
    sources.forEach(s => {
      lines.push(`- **${s.platform}** ${s.platform_username ? `@${s.platform_username}` : ""} (${s.status})`);
    });
    lines.push("");
  }

  if (verifications.length > 0) {
    lines.push("## Verification");
    verifications.forEach(v => lines.push(`- ✓ ${v.signal_type}: ${v.signal_value || "verified"}`));
    lines.push("");
  }

  if (profile.voice) {
    lines.push("## Voice");
    lines.push(profile.voice);
    lines.push("");
  }

  lines.push("---");
  lines.push(`*Generated by [you.md](https://youmd.lovable.app) on ${new Date().toISOString().split("T")[0]}*`);

  return lines.join("\n");
}

export function downloadFile(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
