
-- Seed 6 sample profiles from sampleProfiles.ts into the database
-- These are demo/showcase profiles that will be the canonical data source

INSERT INTO public.profiles (username, name, tagline, bio_short, bio_medium, location, website, avatar_url, cover_url, voice, topics, credibility, links, now_items, values_list, preferences, is_claimed, created_at)
VALUES
  (
    'houston',
    'Houston Golden',
    'Founder, BAMF Media. Building You.md.',
    'Founder building identity infrastructure for the agent internet.',
    'Founded BAMF Media (8-figure growth agency), LinkedIn growth pioneer. Now building You.md — the identity file standard for the agent internet. I ship fast and build in public.',
    'Miami, FL',
    'https://houstongolden.com',
    '/assets/houston-portrait.jpeg',
    'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&h=300&fit=crop',
    'Direct, high-energy, founder-coded.',
    ARRAY['growth marketing', 'AI agents', 'identity protocols'],
    ARRAY['Founded BAMF Media (8-figure agency)', 'LinkedIn growth pioneer', 'Speaker at 20+ conferences'],
    '[{"label":"Website","url":"https://houstongolden.com"},{"label":"LinkedIn","url":"https://linkedin.com/in/houstongolden"},{"label":"X","url":"https://x.com/houstongolden"}]'::jsonb,
    ARRAY['Building You.md', 'Scaling BAMF Media', 'Refining identity protocol'],
    ARRAY['Build in public', 'Extreme ownership', 'Ship fast'],
    '{"tone":"direct, confident, no fluff","formality":"casual-professional","avoid":["corporate jargon","passive voice"],"format":"short paragraphs, punchy sentences"}'::jsonb,
    false,
    now() - interval '12 days'
  ),
  (
    'priya',
    'Priya Sharma',
    'ML engineer @ Anthropic. Alignment researcher.',
    'Research engineer focused on RLHF and alignment.',
    'ML engineer at Anthropic working on RLHF and alignment research. I think in probability distributions and communicate in analogies. Weekend ceramicist. Published 12 papers on reward modeling.',
    'London, UK',
    NULL,
    'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&h=300&fit=crop',
    'Technical but approachable, loves analogies.',
    ARRAY['RLHF', 'alignment', 'reward modeling', 'open-source ML'],
    ARRAY['ML Engineer at Anthropic', '12 published papers on reward modeling', 'Top 1% cited in ML safety'],
    '[{"label":"Scholar","url":"#"},{"label":"GitHub","url":"#"}]'::jsonb,
    ARRAY['Publishing alignment paper Q2', 'Open-sourcing eval framework'],
    ARRAY['Rigorous thinking', 'Open science', 'Making AI safe'],
    '{"tone":"precise, curious, grounded","formality":"academic-casual","avoid":["hype language","unsubstantiated claims"],"format":"structured with headers, as long as needed for precision"}'::jsonb,
    false,
    now() - interval '15 days'
  ),
  (
    'jmarcus',
    'Jordan Marcus',
    'Indie hacker. 3 exits. Building in public.',
    'Building micro-SaaS products in public.',
    '3 exits, 12 failed projects, infinite lessons. Currently running ScreenshotAPI ($8k MRR) and TinyInvoice ($4k MRR). I document everything and believe the best marketing is building in public.',
    'Austin, TX',
    NULL,
    'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=300&fit=crop',
    'Casual, emoji-friendly, shipping energy.',
    ARRAY['indie hacking', 'micro-SaaS', 'building in public', 'solopreneurship'],
    ARRAY['3 successful exits', '$12k+ combined MRR across products'],
    '[{"label":"X","url":"#"},{"label":"Blog","url":"#"},{"label":"Products","url":"#"}]'::jsonb,
    ARRAY['Hit $20k MRR across products', 'Launch AI writing tool'],
    ARRAY['Ship daily', 'Revenue over fundraising', 'Transparency'],
    '{"tone":"casual, encouraging, practical","formality":"very casual","avoid":["corporate speak","long intros"],"format":"short paragraphs, lots of examples, tweet-length when possible"}'::jsonb,
    false,
    now() - interval '19 days'
  ),
  (
    'sato.yuki',
    'Yuki Sato',
    'Staff engineer @ Stripe. Distributed systems.',
    'Distributed systems at scale. Correctness over cleverness.',
    'Staff engineer at Stripe working on payment routing infrastructure. I care about correctness, observability, and well-written RFCs. Maintaining two popular open-source Rust crates with 5k+ combined stars.',
    'Tokyo, Japan',
    NULL,
    'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&h=300&fit=crop',
    'Precise, systems-thinking, dry humor.',
    ARRAY['distributed systems', 'Rust', 'observability', 'payment infrastructure'],
    ARRAY['Staff Engineer at Stripe', '5k+ stars on open-source Rust crates', 'Published in OSDI'],
    '[{"label":"GitHub","url":"#"},{"label":"Blog","url":"#"}]'::jsonb,
    ARRAY['Migrating payment routing to new architecture', 'Writing a technical book on distributed systems'],
    ARRAY['Correctness first', 'Write it down', 'Mentor generously'],
    '{"tone":"precise, thorough, occasionally wry","formality":"professional","avoid":["hand-waving","premature optimization claims"],"format":"RFC-style with tradeoff analysis, thorough"}'::jsonb,
    false,
    now() - interval '64 days'
  ),
  (
    'noor',
    'Noor Al-Rashid',
    'Design engineer. Figma → code. Accessibility advocate.',
    'I bridge design and engineering — specializing in design systems.',
    'Design engineer at Vercel. I build design systems that scale and obsess over accessible, composable interfaces. Previously at Figma. I believe great design should be invisible and great code should read like prose.',
    'Dubai, UAE',
    NULL,
    'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=300&fit=crop',
    'Poetic precision, design-fluent, accessibility-first.',
    ARRAY['design systems', 'accessibility', 'Figma', 'component architecture'],
    ARRAY['Design Engineer at Vercel', 'Previously at Figma', 'WCAG expert'],
    '[{"label":"Dribbble","url":"#"},{"label":"GitHub","url":"#"},{"label":"Blog","url":"#"}]'::jsonb,
    ARRAY['Launching open-source design system', 'Writing accessibility guide'],
    ARRAY['Accessibility is non-negotiable', 'Design is code', 'Less but better'],
    '{"tone":"poetic but precise, design-conscious","formality":"conversational-professional","avoid":["inaccessible patterns","dark patterns"],"format":"visual with examples, concise"}'::jsonb,
    false,
    now() - interval '35 days'
  ),
  (
    'chen.mia',
    'Mia Chen',
    'VC partner @ Sequoia. Climate tech.',
    'Investing in the climate transition at Sequoia.',
    'Partner at Sequoia Capital focusing on climate tech and deep tech. Led investments in 3 unicorns. Stanford MBA. I evaluate founders, not just markets. Writing a weekly newsletter on climate investing.',
    'San Francisco, CA',
    NULL,
    'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?w=800&h=300&fit=crop',
    'Sharp, thesis-driven, high signal.',
    ARRAY['climate tech', 'venture capital', 'deep tech', 'founder evaluation'],
    ARRAY['Partner at Sequoia Capital', 'Led investments in 3 unicorns', 'Stanford MBA'],
    '[{"label":"LinkedIn","url":"#"},{"label":"Newsletter","url":"#"}]'::jsonb,
    ARRAY['Leading Series B for climate startup', 'Publishing annual climate tech report'],
    ARRAY['Founder quality over market size', 'Long-term compounding', 'Radical transparency'],
    '{"tone":"sharp, thesis-driven, high signal","formality":"professional but direct","avoid":["buzzwords without substance","pattern matching clichés"],"format":"thesis statements with supporting evidence, concise"}'::jsonb,
    false,
    now() - interval '28 days'
  )
ON CONFLICT (username) DO UPDATE SET
  name = EXCLUDED.name,
  tagline = EXCLUDED.tagline,
  bio_short = EXCLUDED.bio_short,
  bio_medium = EXCLUDED.bio_medium,
  location = EXCLUDED.location,
  website = EXCLUDED.website,
  avatar_url = EXCLUDED.avatar_url,
  cover_url = EXCLUDED.cover_url,
  voice = EXCLUDED.voice,
  topics = EXCLUDED.topics,
  credibility = EXCLUDED.credibility,
  links = EXCLUDED.links,
  now_items = EXCLUDED.now_items,
  values_list = EXCLUDED.values_list,
  preferences = EXCLUDED.preferences;
